name: CD Pipeline
on:
  push:
    branches:
      - master
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: sudo ./gradlew build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/banerjee-burn-maps/burn-server:latest
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-upload
    steps:
      - name: Deploy New Container
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.FIRE_SERVER_IP }}
          username: ${{ secrets.FIRE_SERVER_USER }}
          password: ${{ secrets.FIRE_SERVER_PASSWORD }}
          script: |
            if [[ $(sudo docker ps -q) ]]; then
              sudo docker kill $(sudo docker ps -q)
            fi
            sudo docker container prune -f
            sudo docker image prune -af
            sudo docker run -p 80:8080 -d ghcr.io/banerjee-burn-maps/burn-server:latest
