# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - test-site-blah-222

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_58f8aa2eb0e24d978bc80a85dfb00cf5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0e1486a20ce846e280e2a40d3efe783a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_58f8aa2eb0e24d978bc80a85dfb00cf5 }}/banerjee-burn-maps/burn-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test-site-blah-222'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ce0a343a490b416b872047187e86441c }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_58f8aa2eb0e24d978bc80a85dfb00cf5 }}/banerjee-burn-maps/burn-server:${{ github.sha }}'